server:
  port: 8083

spring:
  application:
    name: NOTIFICATION-SERVICE
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.javatechie.dto"

eureka:
  client:
    service-url:
      defaultZone : http://swiggy-service-registry:8761/eureka/
